### ISSUE TITLE
点击播放的时候，如何停止其他正在播放的视频

### ISSUE THREAD

**Issue by jinsom** [MoePlayer/DPlayer#119]
点击播放的时候，如何停止其他正在播放的视频，有没有相关的设置。
比如APlayer里面的mutex: true,

**Comment by RexSkz** [comment]
Normally it shouldn't be a feature, because in some situation (such as dplayer in web components) a player can't easily reach other players, let alone stop them. (Using global variable like `window` is another situation.)

Maybe maintaining a "now playing" player set is a better idea, dplayer provides API which can stop one player.

**Comment by jinsom** [comment]
So it is，thanks！

**Comment by RexSkz** [comment]
I found that APlayer uses the `instances` variable to maintain the playing player, but due to [http://cnodejs.org/topic/4f41f516c643fe221005115b](this article), it may have a problem that `instances` variable won't be globally unique, which cause `mutex` can't stop all player. I'll make some funny test for it.

**Comment by DIYgod** [comment]
https://github.com/MoePlayer/APlayer/issues/151

Thanks @RexSkz , `mutex` is not perfect, but it can still meet most case.

**Comment by DIYgod** [comment]
Done. 74eab49a8d64090db3b65f7b9f42502211eb710f
