### ISSUE TITLE
danmaku: why this name?

### ISSUE THREAD

**Issue by justin-hackin** [MoePlayer/DPlayer#124]
you list "danmaku" as a feature but I can't seem to find out what that means.  Is this what you named it after https://en.touhouwiki.net/wiki/Danmaku ?  How does that relate to the player?

**Comment by journey-ad** [comment]
The word "danmaku" is a Japanese word(弾幕) literally means “bullet curtain” and refers to a commentary sharing system in which viewers can plaster comments directly on top of an video. Comments would then scroll across the screen in real time. Comments sometimes got so thick that they resembled a barrage of bullets, aka danmaku.

**Comment by RexSkz** [comment]
[视频弹幕 - 维基百科，自由的百科全书](https://zh.wikipedia.org/wiki/%E8%A7%86%E9%A2%91%E5%BC%B9%E5%B9%95#.E8.AF.8D.E6.BA.90) 

Chinese version only, I can't find other version so this word might be used only in some areas such as China and Japan.

In my understanding, "danmaku" means "comment" in some anime sites, because your comments will show in the video player from the right to the left, which makes them look like danmaku in Touhou (or barrage in real life).

Sorry for confusing you, this doesn't mean that "we can play danmaku games in a video player". 😂

**Comment by notpushkin** [comment]
@RexSkz @DIYgod perhaps add this to FAQ / point it out in other way somehow? I have guessed it since I've seen this effect on some asian video sites but many people would be completely unaware about its meaning.
