### ISSUE TITLE
Style for live mode

### ISSUE THREAD

**Issue by DIYgod** [MoePlayer/DPlayer#76]
- Hide play bar
- Hide total time
- Hide danmaku input

**Comment by RexSkz** [comment]
I was working to hack DPlayer (Discuz! version) for live, these are what I did:

1. Write a backend for live danmaku, using long-polling;
2. Set a variable `liveMode = enablehls && Hls.isSupported()`;
3. Set display for `.dplayer-bar-wrap, .dplayer-time` to `'none'` when `liveMode`;
4. Generally live danmaku must contains a user id. `pushDanmaku` in `sendComment` must be disabled when `liveMode && danmakuData.userId === currentUser.id`, because the long-polling will soon get the danmaku data and then push it to screen.

This is what it now looks like (live stream currently not available so it shows black screen):

![image](https://cloud.githubusercontent.com/assets/27483702/26489569/72d2a262-423a-11e7-8234-efd2bbc0731c.png)

Because I have change plenty of codes for personal use, so I can't make PR right now, but after my graduation (in few month) I'll try to become a contributor ^_^.

**Comment by DIYgod** [comment]
Thanks for you information. But why don't you use WebSocket for a better experience and performance?

**Comment by RexSkz** [comment]
Because of our school's bad network support. Websocket is not supported for school's firewall lol.

Maybe add an option such as `method = 'websocket' (default), 'long-poll' or 'poll'` is a good way.

**Comment by DIYgod** [comment]
Done. https://github.com/MoePlayer/DPlayer/commit/36d61c4d61869186b38bcfeda9c8dadd630d9a47
